version: '3.7'

services:
  nfgoverlay-fitb:
    image: nfg/nfgoverlay-fitb:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TERM=xterm-256color
    tty: true
