export default [
  '12 Angry Men',
  'American History X',
  'Apocalypse Now',
  'Back to the Future',
  'Django Unchained',
  'Fight Club',
  'Forrest Gump',
  'Indiana Jones and the Raiders of the Lost Ark',
  'Kung Fury',
  'Pulp Fiction',
  'Saving Private Ryan',
  'Seven Samurai',
  'Star Wars: The Empire Strikes Back',
  'Star Wars',
  'Terminator 2: Judgment Day',
  'The Dark Knight',
  'The Good, the Bad and the Ugly',
  'The Green Mile',
  'The Lion King',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Lord of the Rings: The Return of the King',
  'The Lord of the Rings: The Two Towers',
  'The Shawshank Redemption',
  'The Silence of the Lambs',
  'The Usual Suspects',
  "It's a Wonderful Life",
  "One Flew Over the Cuckoo's Nest",
  "Schindler's List"
];
